### ISSUE TITLE
bug: negative number displays as 0

### ISSUE THREAD

**Issue by mercer08** [TuckerMassad/react-animated-counter#7] opened 2024-02-18 04:07 UTC
i have bug report, negative number displays as 0, is there any soluation for this?

**Comment by TuckerMassad** [comment] 2024-02-18 20:28
Hi @mercer08. Great find - I'll definitely have this addressed within the next couple of days. I'll keep this issue thread once the package has been updated.

**Comment by TuckerMassad** [comment] 2024-02-19 19:44
Hi @mercer08. If you would kindly bump your package version to `1.7.7` the issue should now be resolved. Please let me know if things are working as expected and/or you see any other issues in the meantime! 😄

**Comment by TuckerMassad** [comment] 2024-02-22 13:36
Closing this out as the issue is resolved + no further comments on it 👍

**Closed by TuckerMassad** 2024-02-22 13:36 UTC
Labels: bug, Resolved
